### ISSUE TITLE
beam search generating more that just the top sentence

### ISSUE THREAD

**Issue by anisdismail** [lucidrains/reformer-pytorch#102]
In the generate function implemented here, I can't seem to find any way to have access to more the top sentence generated (the top 5 sentences for example). Are there any plans for implementing something like so, or it already exists?

**Comment by lucidrains** [comment]
@anisdismail I don't have a beam search yet, you should submit a PR :)

**Comment by anisdismail** [comment]
sure! will do very soon! Will this mean you are currently working on one or can I collaborate and try to work on one?

**Comment by lucidrains** [comment]
I have my hands full at the moment, you should go ahead and make one! maybe you could even release it as your own package
