### ISSUE TITLE
Reformer Encoder Decoder Architecture

### ISSUE THREAD

**Issue by AliOskooeiTR** [lucidrains/reformer-pytorch#103]
There seems to be a minor error in the documentation. In the example, ```enc_max_seq_len ``` has been set to ```DE_SEQ_LEN ``` and the ```dec_max_seq_len ``` is set to ```EN_SEQ_LEN ```.

**Comment by lucidrains** [comment]
@AliOskooeiTR oh lol, i can see why that looks like an error

DE actually stands for German, and EN stands for English. It's suppose to be German -> English translation lol

**Comment by AliOskooeiTR** [comment]
ahh I see! such a conincidence :D I am trying to use the encoder decoder for a summarisation task. I seem to be getting an assertion error when setting the ```dec_num_tokens ``` to a small number such as 100 or 200. Is there a hard coded limit to how small the decoder output can be? I just noticed the error now so I haven't thoroughly investigated it.

**Comment by lucidrains** [comment]
@AliOskooeiTR Ohh, I think the only limit is if it is smaller than the bucket size. This variant of attention network is designed for very long sequences, so you can actually just set the max seq len to something really large! It is only meant for making sure input sequences do not exceed that length.

**Comment by AliOskooeiTR** [comment]
Thank you for your quick response! So I will just set it to something large and if it's smaller than that it should be fine anyway.

**Comment by lucidrains** [comment]
No problem! Since the Reformer, I have explored other types of sparse attention networks and can highly recommend Routing Transformer (https://github.com/lucidrains/routing-transformer)

**Comment by AliOskooeiTR** [comment]
I am interested in training on long input sequences (10000+ tokens). Training time/memory is definitely a problem currently specially with RNN-based techniques. Reformer is known to tackle some of these issues with LSH. That's why I am interested in trying it out. But I will definitely look into the routing transformer as well. I will keep you posted how the experiments go. Thanks again for your help.

**Comment by lucidrains** [comment]
@AliOskooeiTR Yes, Routing Transformer (and all the variants of Transformers I implement), are meant to stretch attention as far and wide as possible!

**Comment by AliOskooeiTR** [comment]
@lucidrains Thanks for bringing it to my attention. I will definitely try it out!

**Comment by alexgaskell10** [comment]
@AliOskooeiTR did you try this in the end? Considering doing something similar and would love to hear how you got on.
