### ISSUE TITLE
Attn weight size from Recorder

### ISSUE THREAD

**Issue by nitinnairk** [lucidrains/reformer-pytorch#107]
Thanks for the quick response as always!
The recording now returns a size of 2048*2176 which doesn't seem right 🤔

_Originally posted by @nitinnairk in https://github.com/lucidrains/reformer-pytorch/issues/106#issuecomment-653695834_

**Comment by lucidrains** [comment]
It's right because the number of memory key/values you set is 128, so it is 2048 + 128

**Comment by lucidrains** [comment]
I send back the attention on the memory too

**Comment by nitinnairk** [comment]
Oh! sweet.
Thanks!
