### ISSUE TITLE
Feed Forward Dimension for Reformer

### ISSUE THREAD

**Issue by anisdismail** [lucidrains/reformer-pytorch#108]
I was checking the paper and it seems there is a difference between the value set for the feed forward dimension and model dimension, and I don't think this difference is accounted for in this implementation. Are there any plans to add this? Thanks ;)

**Comment by lucidrains** [comment]
You can actually set this using the `ff_mult` keyword! https://github.com/lucidrains/reformer-pytorch#customizing-feedforward the dff would be equal to the dim * ff_mult

**Comment by lucidrains** [comment]
In most transformer implementations, the dff is about 4 times the size of the dmodel
