### ISSUE TITLE
batch size incompatible for mem_kv

### ISSUE THREAD

**Issue by keroro824** [lucidrains/reformer-pytorch#112]
Thanks for the efforts! This is a wonderful repo for researchers:). 

I found mem will have the wrong shape when batch size is larger than 1.

This can be replicated through the testing colab:

import torch
from reformer_pytorch import ReformerLM

seq_len = 32768

model = ReformerLM(
    num_tokens= 20000,
    dim = 512,
    depth = 12,
    max_seq_len = seq_len,
    heads = 8,
    lsh_dropout = 0.1,
    causal = True,        # auto-regressive or not
    bucket_size = 64,     # average size of qk per bucket, 64 was recommended in paper
    n_hashes = 4,         # 4 is permissible per author, 8 is the best but slower
    ff_chunks = 100,      # number of chunks for feedforward layer, make higher if there are memory issues
    weight_tie = False,   # tie parameters of each layer for no memory per additional depth
    attn_chunks = 8,        # process lsh attention in chunks, only way for memory to fit when scaling to 16k tokens
    use_full_attn = False,   # use full self attention, for comparison
    num_mem_kv=128
).cuda()

x = torch.randint(0, 20000, (2, seq_len)).long().cuda()
y = model(x)
y.sum().backward()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-ce5b3605bb3b> in <module>()
     22 
     23 x = torch.randint(0, 20000, (2, seq_len)).long().cuda()
---> 24 y = model(x)
     25 y.sum().backward()

14 frames
/usr/local/lib/python3.6/dist-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, keys, input_mask, input_attn_mask, context_mask, **kwargs)
    521         use_full_attn = self.use_full_attn or kv_len <= self.full_attn_thres
    522 
--> 523         x = torch.cat((x, mem, keys), dim=1)
    524         qk = self.toqk(x)
    525         v = self.tov(x)

RuntimeError: Sizes of tensors must match except in dimension 0. Got 2 and 1 (The offending index is 1)

**Comment by lucidrains** [comment]
@keroro824 Hey Beidi! Thanks for catching the :beetle:  I've fixed it in the latest version!
