### ISSUE TITLE
what is the meaning of "buckets_and_t = seqlen * buckets + (ticker % seqlen)" ?

### ISSUE THREAD

**Issue by onedreame** [lucidrains/reformer-pytorch#117]
what is the meaning of "buckets_and_t = seqlen * buckets + (ticker % seqlen)" ? In my opinion, just sort_key_val(buckets) is ok?

**Comment by lucidrains** [comment]
@onedreame that line will ensure that every token in every hash round is assigned a unique integer index, so that later we can unsort it back to the original order

ex.
```python
seq = [a, b, c]
buckets = [0, 0, 1, 2, 3, 3]  # there are 2 buckets with 2 rounds of hashing

seqlen * ticker = [0, 0, 3, 6, 9, 9]
ticker % seqlen = [0, 1, 2, 0, 1, 2]
buckets_and_t = [0, 1, 5, 6, 10, 11]  # as you can see, each token across 2 hash rounds have unique id
```
