### ISSUE TITLE
Are `emb_dim` and `dim` equal by default

### ISSUE THREAD

**Issue by rookiez7** [lucidrains/reformer-pytorch#133]
In `class ReformerLM`,there are 2 parameters about dim,`emb_dim` and 'dim'. i find you use `emb_dim = default(emb_dim, dim)`.Is it default that `emb_dim` and  `dim` are equal.i try make them diff,then erro occurs.`self.norm = nn.LayerNorm(emb_dim)` caused the problem i think.

**Comment by lucidrains** [comment]
I believe this has been fixed in the latest!
