### ISSUE TITLE
Default embeddings are rotary Embeddings not Axialpositional Embeddings as stated by the documentation

### ISSUE THREAD

**Issue by samuelgoodall** [lucidrains/reformer-pytorch#146]
Thanks for creating this great Repository.
In the ReformerLM the Rotary-Embeddings Flag is set to true as standard as opposed to the documentation witch states that Axial-Positional-Encodings would be used.

**Comment by lucidrains** [comment]
@samuelgoodall oh yes, you are right! fixed in v1.4.3 :D
