### ISSUE TITLE
half precision on long sequence doesn't work

### ISSUE THREAD

**Issue by sklin93** [lucidrains/reformer-pytorch#148]
The linked example here: https://colab.research.google.com/drive/1awNgXYtjvUeXl1gS-v1iyDXTJJ-fyJIK will give errors for einsum operation: `expected scalar type Float but found Half`

**Comment by ontocord** [comment]
Same problem

**Comment by lucidrains** [comment]
i'm not sure what is wrong, but i updated it to O2 optimization and it started working

**Comment by lucidrains** [comment]
@sklin93 oh nvm, i found the problem! should be fixed in 1.4.4 :pray:
