### ISSUE TITLE
not find axial_positional_embedding.py

### ISSUE THREAD

**Issue by wuyulong666** [lucidrains/reformer-pytorch#153]
https://github.com/lucidrains/reformer-pytorch/blob/66a19b6caf481a880c97d331306aba55d2ae4b9c/reformer_pytorch/reformer_pytorch.py#L12

**Comment by lucidrains** [comment]
@wuyulong666 `pip install reformer-pytorch` before running

**Comment by wuyulong666** [comment]
@lucidrains thanks
