### ISSUE TITLE
Implement sampling

### ISSUE THREAD

**Issue by paulnorman1** [lucidrains/reformer-pytorch#17]
Hello! Thank you for this repo!

Can you please implement sampling in the example file, so we'd be able to generate outputs from the model (as done in GPT-2)?

**Comment by lucidrains** [comment]
@paulnorman1 hello, the code in the example folder does just that! (but i haven't added the sampling) also to be done is proper caching during evaluation to make things fast

**Comment by paulnorman1** [comment]
Excuse me, I'm not proficient in ML (I mainly test public code on my datasets). I don't see any code for generating output from the model in train.py. Is it something that you're planning on implementing?

**Comment by lucidrains** [comment]
yup, i will implement it at some point, most possibly with nucleus sampling

**Comment by paulnorman1** [comment]
Great, thanks!

**Comment by lucidrains** [comment]
@paulnorman1 I've updated the example to generate text!

**Comment by paulnorman1** [comment]
Awesome, thank you so much! Can't wait to test.
