### ISSUE TITLE
GLUE Training/Evaluation Codebase

### ISSUE THREAD

**Issue by zbloss** [lucidrains/reformer-pytorch#18]
Hey I am planning to start building a codebase to both train and evaluate this model on the GLUE tasks. 

Are you working on this already? If not, I can write some code and make a pull request.

**Comment by lucidrains** [comment]
@zbloss hello! I'm actually working on proteins! go for it, would be happy to accept a PR

**Comment by zbloss** [comment]
I'm on it!
