### ISSUE TITLE
example

### ISSUE THREAD

**Issue by 2020zyc** [lucidrains/reformer-pytorch#2]
Hi, can you release an autoregressive example first? Such as a reformer language model example.
So we can test it in an all-round way.
Thanks much.

**Comment by lucidrains** [comment]
<img width="811" alt="Screen Shot 2020-01-14 at 6 55 57 PM" src="https://user-images.githubusercontent.com/108653/72401443-da498380-3700-11ea-9237-131f529e6ae4.png">

Sure, I'll upload a sample usage script some time this week

**Comment by lucidrains** [comment]
<img width="944" alt="Screen Shot 2020-01-15 at 10 02 24 AM" src="https://user-images.githubusercontent.com/108653/72459598-fe987500-377f-11ea-80db-e85348ffaca4.png">

**Comment by lucidrains** [comment]
uploaded a training script here to help you get started https://github.com/lucidrains/reformer-pytorch/blob/master/example/train.py hope that helps!
