### ISSUE TITLE
Is training slow?

### ISSUE THREAD

**Issue by paulnorman1** [lucidrains/reformer-pytorch#20]
I'm running the example script (with no change) on Nvidia V100 and the training seems to go very slow. Each batch takes a few seconds (≅3.2sec). What can be the problem?

EDIT: After some comparisons with other models, it doesn't seem to be relatively slow. But I still wanted to know other people's experiences.

**Comment by lucidrains** [comment]
The point of this network is to allow for sequence lengths that normal attention could never do. If you toggle on the use_full_attn flag, that should give you an idea of how a regular transformer would behave at the same length. For normal setups, anything greater than 2048 usually starts to break

**Comment by paulnorman1** [comment]
Gotcha, so it's due to the sequence length being 4096 I guess.

Not related, what does `num_tokens` for?

**Comment by lucidrains** [comment]
Yea, 4096 is really long already! `num_tokens` is for the number of unique things you want the network to learn the relationships of with attention. For language models, this would be the number of unique subwords or characters of a string chopped up by your favorite encoding technique, assigned an id.

**Comment by paulnorman1** [comment]
Thank you very much for taking your time explaining! I appreciate that.

**Comment by paulnorman1** [comment]
Another unrelated question, if I may ask here: is it possible to train the model on short sequences and then fine-tune on larger sequences (setting different SEQ_LEN each time)?

**Comment by Phirefly9** [comment]
Reading through issues and I'll jump in and answer.

SEQ_LEN must be the same for a trained/fine-tuned model.  The sequence_length in the transformer architecture is used to directly influence the positional embeddings and tell transformer where in the sequence it is

for the code in this repo see https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L54

The positional embedding will be very different if you change SEQ_LEN, it would no longer be fine tuning, but training the model from scratch

**Comment by paulnorman1** [comment]
Understood, thanks a lot! @Phirefly9
