### ISSUE TITLE
Applying input mask?

### ISSUE THREAD

**Issue by harrik** [lucidrains/reformer-pytorch#24]
Testing around with simple next token prediction. Sample data is separate sentences with padding. Is there a way to apply an input mask for the paddings?

**Comment by lucidrains** [comment]
Just added it here and bumped a new package! https://github.com/lucidrains/reformer-pytorch/pull/25 Feel free to reopen the issue if doesn't work or if you find a bug. Simply pass a boolean mask of size (batch size, seq len) with `False` in the positions of padding

**Comment by erickrf** [comment]
In an encoder-decoder setting, it might be interesting to have separate masks for the context and self attention, right? More specifically, `LSHSelfAttention` class would concat both masks, I believe. I'm working on something along those lines, and can submit a PR when it's done.

**Comment by lucidrains** [comment]
@erickrf ohh, i totally missed this. yea, I could add a `context_mask`, which will be simply concatenated to the `input_mask` before being passed to the LSH attention operations

**Comment by lucidrains** [comment]
@erickrf https://github.com/lucidrains/reformer-pytorch/pull/38
