### ISSUE TITLE
Don't understand how REFORMER tokenizes words

### ISSUE THREAD

**Issue by alexvaca0** [lucidrains/reformer-pytorch#33]
Hi, I've been a couple of months working with transformers models with the transformers library (https://huggingface.co/transformers/index.html), and I want to try your ReformerLM to see if I can train a good language model for spanish using this new technology and your library. Therefore, first of all I want to say thank you for developing this library and for implementing the Reformer, since the code provided by google together with the paper was not very "usable", in that it wasn't implemented in parametric classes in an ordered manner. So thanks for the effort. The thing is, I don't understand what kind of tokenization you're using in this model, as in the example there doesn't seem to be any tokenization step, nor have you any tokenizer class to train your own tokenizer with BPE or other method. Maybe I'm getting something wrong about the model, but I'd like to know how you deal with this issue to introduce the inputs to the model. Thank you in advance for your response, and if I manage to make the ReformerLM work, I'll try to make a Generator like GPT-2 based on this architecture instead of the transformer architecture, so that we can expand this library. Regards, Alejandro.

**Comment by lucidrains** [comment]
@alexvaca0 So this library is actually tokenizer agnostic. You can choose your own method for tokenizing. I personally use `youtokentome`, but the new speedy Rust-based `tokenizer` by huggingface looks great too.

**Comment by lucidrains** [comment]
@alexvaca0 it seems like everyone I run into wants to build a generative model for text, even though Reformer can be used for so much more. I'll see if I can provide an end to end example, perhaps as a command line tool, that will allow you to train one easily on any corpus of text.

**Comment by paulnorman1** [comment]
@lucidrains That would be awesome!

**Comment by lucidrains** [comment]
Closing this in favor of keeping the more recent related issue open
