### ISSUE TITLE
The first example in your README doesn't work :( 

### ISSUE THREAD

**Issue by alexvaca0** [lucidrains/reformer-pytorch#34]
Here's the error: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-36-0b51ec321dc8> in <module>
     21 
     22 x = torch.randint(0, 20000, (1, 8192)).long().cuda()
---> 23 y = model(x) # (1, 8192, 20000)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, **kwargs)
    499 
    500         x = self.to_model_dim(x)
--> 501         x = self.reformer(x, **kwargs)
    502         return self.to_logits(x)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, keys)
    479         x = torch.cat([x, x], dim = -1)
    480         self.set_reversible_args(keys = keys)
--> 481         x = self.layers(x)
    482         return torch.stack(x.chunk(2, dim=-1)).sum(dim=0)
    483 

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/revtorch/revtorch.py in forward(self, x)
    197         :return: Output tensor
    198         '''
--> 199         x = _ReversibleModuleFunction.apply(x, self.reversible_blocks, self.eagerly_discard_variables)
    200         return x

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/revtorch/revtorch.py in forward(ctx, x, reversible_blocks, eagerly_discard_variables)
    144         for block in reversible_blocks:
    145             assert (isinstance(block, ReversibleBlock))
--> 146             x = block(x)
    147         ctx.y = x.detach() #not using ctx.save_for_backward(x) saves us memory by beeing able to free ctx.y earlier in the backward pass
    148         ctx.reversible_blocks = reversible_blocks

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/revtorch/revtorch.py in forward(self, x)
     47         with torch.no_grad():
     48             self._init_seed('f')
---> 49             y1 = x1 + self.f_block(x2)
     50             self._init_seed('g')
     51             y2 = x2 + self.g_block(y1)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x)
     80     def forward(self, x):
     81         x = self.norm(x)
---> 82         return self.fn(x)
     83 
     84 class Chunk(nn.Module):

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x)
    105 
    106     def forward(self, x):
--> 107         return self.fn(x, *self.args, **self.kwargs)
    108 
    109 # LSH attention as described in https://openreview.net/pdf?id=rkgNKkHtvB

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, keys)
    394 
    395         mem = self.mem_kv.expand(b, m, e)
--> 396         keys = default(keys, torch.empty(b, 0, e, dtype=mem.dtype, device=device))
    397 
    398         kv_len = t + m + keys.shape[1]

RuntimeError: sizes must be non-negative
.....................................................................................

This error occurs when using exactly the same example you have in your README...
import torch
from reformer_pytorch import ReformerLM

model = ReformerLM(
    num_tokens= 20000,
    dim = 1024,
    depth = 12,
    max_seq_len = 8192,
    heads = 8,
    lsh_dropout = 0.1,
    emb_dim = 128,        # embedding factorization for further memory savings
    causal = True,        # auto-regressive or not
    bucket_size = 64,     # average size of qk per bucket, 64 was recommended in paper
    n_hashes = 4,         # 4 is permissible per author, 8 is the best but slower
    ff_chunks = 200,      # number of chunks for feedforward layer, make higher if there are memory issues
    weight_tie = False,   # tie parameters of each layer for no memory per additional depth
    attn_chunks = 8,        # process lsh attention in chunks, only way for memory to fit when scaling to 16k tokens
    num_mem_kv = 128,       # persistent learned memory key values, from all-attention paper
    twin_attention = False, # both branches of the reversible network will be attention
    use_full_attn = False,  # use full self attention, for comparison
    full_attn_thres = 1024, # use full attention if context length is less than set value
    use_scale_norm = False  # use scale norm from 'Transformers without tears' paper
).cuda()

x = torch.randint(0, 20000, (1, 8192)).long().cuda()
y = model(x) # (1, 8192, 20000)
.....................................................................
​

**Comment by alexvaca0** [comment]
The same error occurs in the second example:

------------------------------------------------------------------

import torch
from reformer_pytorch import Reformer

model = Reformer(
    dim = 512,
    depth = 12,
    max_seq_len = 8192,
    heads = 8,
    lsh_dropout = 0.1,
    causal = True
).cuda()

x = torch.randn(1, 8192, 512).cuda()
y = model(x) # (1, 8192, 512)
-----------------------------------------------------
ERROR:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-36-0b51ec321dc8> in <module>
     21 
     22 x = torch.randint(0, 20000, (1, 8192)).long().cuda()
---> 23 y = model(x) # (1, 8192, 20000)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, **kwargs)
    499 
    500         x = self.to_model_dim(x)
--> 501         x = self.reformer(x, **kwargs)
    502         return self.to_logits(x)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, keys)
    479         x = torch.cat([x, x], dim = -1)
    480         self.set_reversible_args(keys = keys)
--> 481         x = self.layers(x)
    482         return torch.stack(x.chunk(2, dim=-1)).sum(dim=0)
    483 

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/revtorch/revtorch.py in forward(self, x)
    197         :return: Output tensor
    198         '''
--> 199         x = _ReversibleModuleFunction.apply(x, self.reversible_blocks, self.eagerly_discard_variables)
    200         return x

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/revtorch/revtorch.py in forward(ctx, x, reversible_blocks, eagerly_discard_variables)
    144         for block in reversible_blocks:
    145             assert (isinstance(block, ReversibleBlock))
--> 146             x = block(x)
    147         ctx.y = x.detach() #not using ctx.save_for_backward(x) saves us memory by beeing able to free ctx.y earlier in the backward pass
    148         ctx.reversible_blocks = reversible_blocks

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/revtorch/revtorch.py in forward(self, x)
     47         with torch.no_grad():
     48             self._init_seed('f')
---> 49             y1 = x1 + self.f_block(x2)
     50             self._init_seed('g')
     51             y2 = x2 + self.g_block(y1)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x)
     80     def forward(self, x):
     81         x = self.norm(x)
---> 82         return self.fn(x)
     83 
     84 class Chunk(nn.Module):

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x)
    105 
    106     def forward(self, x):
--> 107         return self.fn(x, *self.args, **self.kwargs)
    108 
    109 # LSH attention as described in https://openreview.net/pdf?id=rkgNKkHtvB

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/miniconda/envs/distilbert_env/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py in forward(self, x, keys)
    394 
    395         mem = self.mem_kv.expand(b, m, e)
--> 396         keys = default(keys, torch.empty(b, 0, e, dtype=mem.dtype, device=device))
    397 
    398         kv_len = t + m + keys.shape[1]

RuntimeError: sizes must be non-negative

**Comment by alexvaca0** [comment]
The environment I'm using is:

name: distilbert_env
dependencies:
  - colorcet=2.0.2
  - cudatoolkit=9.0
  - cudnn=7.1.2
  - keras-gpu=2.2.2
  - jupyter=1.0.0
  - holoviews=1.12.6
  - nb_conda=2.2.1
  - scikit-learn=0.19.1
  - pandas=0.23.0
  - pip=19.2.3
  - pytorch=0.4.1
  - tqdm=4.36.1
  - pip:
      - transformers==2.1.1

**Comment by lucidrains** [comment]
@alexvaca0 Hi Alex! Thank you for your interest in this library. I notice that your pytorch library is quite dated. Could you upgrade and try again and see if it works. I admittedly haven't tested this for older versions of pytorch and will update the dependencies if upgrading works for you. You can always execute the Colab links in the readme to verify that the code works on the latest versions.

**Comment by alexvaca0** [comment]
Thanks a lot @lucidrains , you were right, using an updated version of pytorch it works :)
