### ISSUE TITLE
Combining Attention & Self-Attention in Reformer ?

### ISSUE THREAD

**Issue by pabloppp** [lucidrains/reformer-pytorch#35]
I have noticed that in the original Transformers paper, in the **decoder** blocks they alternate between masked self-attention and regular-attention over the outputs of the encoder:
![image](https://user-images.githubusercontent.com/4237014/74528042-814f5400-4f27-11ea-9b72-821e0f9a760b.png)
This allows the model to take attention to the previously generated words before choosing what parts of the decoder output to pay attention to.

Please, correct me if I'm wrong, but in the Reformer module and ReformerLM modules of this repository, I believe that if the encoder outputs are passed as an extra input to the decoder (with the "keys" parameters, like in the translation example), the model will only apply attention to it, and will not perform any self-attention on the decoder input, so every step of the decoder the model is only able to use the current word as query, and is not able to look at the previously generated words, right? 

And what's more, the "causal" flag will apply a mask on the attention from the encoder keys, so when the model generates the word in position N we only pay attention to the Keys in position < N

Would it make sense to allow the choice to combine self-attention (k == v == q), where the mask should be applied if we want it to be causal, with regular attention(q != k == v) using the passed keys, where causality no longer makes a lot of sense because we might want to be able to focus on a word at the end of the sentence if the language has a different word ordering?

**Comment by lucidrains** [comment]
@pabloppp Good observations! In the past, for simplicity's sake, I have combined the self-attention and "regular" attention, into one layer, which has worked for me for a number of tasks, although I have not done a head to head comparison with the original architecture. To keep the readme concise, and to make the reversible architecture work (it only accepts two functions F and G), I kept it the simplified way. However, I wouldn't oppose trying to be more faithful to the original architecture, but it would require some decisions on the reversible net, and which 2 of the now 3 components to be slotted into F and G.

**Comment by lucidrains** [comment]
(The most faithful reproduction would be to do self-attention + feedforward and then regular-attention + feedforward, alternating in that manner.)

**Comment by lucidrains** [comment]
```Would it make sense to allow the choice to combine self-attention (k == v == q), where the mask should be applied if we want it to be causal, with regular attention(q != k == v) using the passed keys, where causality no longer makes a lot of sense because we might want to be able to focus on a word at the end of the sentence if the language has a different word ordering?``` Just read this. That's what I have!

**Comment by pabloppp** [comment]
>Just read this. That's what I have!

Okay, so maybe I was not able to understand the implementation... You're saying that if the user passes both an input and a key parameter to the model like `decoder(yi, keys = enc_keys)` then your implementation will apply masked self-attention to `yi`, then apply non-masked regular attention over `enc_keys`?

If that's so, it's really awesome, and then this issue makes no sense and you could close it.

Again, thanks for your awesome work!! I am currently using your library for a couple of projects and it definitely works like a charm.

**Comment by lucidrains** [comment]
@pabloppp yes, exactly, except they are done in one layer in the same attention matrix. each token attends to all tokens of the past as well as the `enc_keys`

**Comment by pabloppp** [comment]
Oh, seems like a clever approach 😮 thank you!
