### ISSUE TITLE
torch.nn.DataParallel causes strange GPU memory overflow

### ISSUE THREAD

**Issue by ewrfcas** [lucidrains/reformer-pytorch#36]
Thanks for your great job!
When i am testing this model with code as

```
import torch
from reformer_pytorch import ReformerLM
from torch.nn import functional as F

model = ReformerLM(
    num_tokens=20000,
    dim=1024,
    depth=24,
    max_seq_len=1024,
    heads=16,
    lsh_dropout=0.1,
    emb_dim=1024,  # embedding factorization for further memory savings
    causal=True,  # auto-regressive or not
    bucket_size=64,  # average size of qk per bucket, 64 was recommended in paper
    n_hashes=8,  # 4 is permissible per author, 8 is the best but slower
    ff_chunks=200,  # number of chunks for feedforward layer, make higher if there are memory issues
    weight_tie=False,  # tie parameters of each layer for no memory per additional depth
    attn_chunks=8,  # process lsh attention in chunks, only way for memory to fit when scaling to 16k tokens
    num_mem_kv=0,  # persistent learned memory key values, from all-attention paper
    twin_attention=False,  # both branches of the reversible network will be attention
    use_full_attn=True,  # use full self attention, for comparison
    full_attn_thres=128,  # use full attention if context length is less than set value
    use_scale_norm=False  # use scale norm from 'Transformers without tears' paper
).cuda()

model = torch.nn.DataParallel(model)
model.train()
x = torch.randint(0, 20000, (8, 1024)).long().cuda()
y = torch.randint(0, 20000, (8, 1024)).long().cuda()
pred = model(x)
loss = F.cross_entropy(pred.transpose(1, 2), y, reduction='mean')
loss.backward()
import ipdb
ipdb.set_trace()
```
When without ```model = torch.nn.DataParallel(model)```, 7616M memory is used.
But after I add ```model = torch.nn.DataParallel(model)```, it causes OOV while 8 gpus has 16GB memory for each.
I think maybe it is the problem of revtorch?

**Comment by lucidrains** [comment]
@ewrfcas very likely so. I have not tested extensively on multi-GPU, and some other issue has pointed out similar problems with RevTorch when trying to go distributed

**Comment by lucidrains** [comment]
@ewrfcas I welcome any help debugging this. I am working with only 2 GPUs, and one of them is on a long running job that I am on a deadline with

**Comment by lucidrains** [comment]
@zbloss Hey Zach, I noticed that the self-supervised learning script you provided offers multi-GPU support. Have you tried that with Reformer successfully?

**Comment by ewrfcas** [comment]
@lucidrains I will try to debug for this problem.
But I haven't seen anyone meet the same problem in https://github.com/RobinBruegger/RevTorch

**Comment by lucidrains** [comment]
Thanks! This may be one of the last hurdles to overcome. I've been using the library on a single GPU and it is seemingly working well!

**Comment by zbloss** [comment]
I have also been running into memory issues, and I plan to remove this nn.DataParellel until we can get it sorted out.

In the meantime, I am working on adding support for Microsoft's new DeepSpeed library, which may take care of all of this for us.

**Comment by lucidrains** [comment]
@zbloss Amazing!

**Comment by lucidrains** [comment]
@ewrfcas Hello again! So I was able to do a training run overnight with 2 GPUs and memory seems to be stable and working fine (at least the reversible network part). I verified it then again by running it with 1 GPU and memory doubled as expected

Lemme know!

**Comment by lucidrains** [comment]
@ewrfcas I made some changes to the way random number generator is handled, so you will need to update the package before trying again

**Comment by Phirefly9** [comment]
I would recommend that dataparallel pretty much never be used for models and data of the size this network is targeting.  Distributed is usually always faster even for smaller numbers of GPUs in my experience

**Comment by lucidrains** [comment]
@Phirefly9 I'm going to try pytorch lightning with their new TPU support with Reformer this week on the new paid Colab plan, and hopefully iron out any distributed issues!

**Comment by ewrfcas** [comment]
@lucidrains Thanks for your attention. I will try it again.

**Comment by lucidrains** [comment]
closing because it's been verified to work on my end
