### ISSUE TITLE
parameter change test on reformer model

### ISSUE THREAD

**Issue by fcampagne** [lucidrains/reformer-pytorch#37]
I did a parameter change test similar to the one offered in torchtest with a pytorch_reformer model (using reformer_pytorch==0.12.7). 

I got the following result:

> utils.VariablesChangeException: #OK: 31 #wrong: 2 Parameters: 
> E            reformer.reformer.layers.reversible_blocks.0.f_block.fn.fn.mem_kv
> E            reformer.reformer.layers.reversible_blocks.1.f_block.fn.fn.mem_kv

indicating that the mem_kv parameters are not updated during an optimizer step. 
I looked at the code of LSHAttention and see this line:
> keys = default(keys, torch.empty(b, 0, e, dtype=mem.dtype, device=device))
I think that the call to torch.empty should include the require_grad=True parameter.

**Comment by lucidrains** [comment]
@fcampagne What was the value that you set `num_mem_kv` to when instantiating the Reformer? https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L425 I wonder if it is perhaps because there are no memory key values at all

**Comment by fcampagne** [comment]
I see, there a default of zero and I am using the default in this code.

**Comment by fcampagne** [comment]
Changing to a value larger than zero fixed this. Thanks for the quick help.

**Comment by lucidrains** [comment]
@fcampagne no problem! thank you for reporting, let me fix this issue right now with a patch

**Comment by lucidrains** [comment]
fixed here https://github.com/lucidrains/reformer-pytorch/commit/f21471068323b398f5e1b63bea0dbe7472933ebb

**Comment by fcampagne** [comment]
Nice. Thanks.
