### ISSUE TITLE
Glue example

### ISSUE THREAD

**Issue by liangular** [lucidrains/reformer-pytorch#48]
Hi, first of all thanks for the great work!

I was wondering how the Glue example is supposed to do any classification. There is no classification head added anywhere in the example for the classification tasks. From what I see in the example it simple takes the argmax(-1) from the [batch, sequence_length, number_of_tokens] output of the ReformerLM which is nonsense, isn't it?.  I would expect to set 1. `return_embeddings = True` and 2. `causal=False` and take one output token i.e [:,0,:] and add maybe 2 Linear layers on top of that like BERT does, or average over all the tokens, since our task is classification.

Are my assumptions right, or am I getting something wrong?

**Comment by lucidrains** [comment]
ah yea, it does appear to be incorrect. circling in @zbloss since he added that script

**Comment by liangular** [comment]
Ok, thanks for the answer. @lucidrains  Another question just for clarification. Setting `causal=True` leads to a bidirectional behaviour like BERTs, right? If thats the case I could add a ReformerClassifier in a pull request since I am for sure not the only one who wants to do classification with this repo and the current glue example leads to some confusion.

**Comment by lucidrains** [comment]
@liangular the `causal` flag of `True` actually makes the network auto-regressive (unidirectional), so in this case you would want to turn it off. I made a simple gist of a classifier, if that is what you are aiming for https://gist.github.com/lucidrains/5c4151acf9fa73ab1ab93a8e0aa920f2

**Comment by lucidrains** [comment]
removing glue for now until there is a revised submission
