### ISSUE TITLE
split_heads()

### ISSUE THREAD

**Issue by opsuisppn** [lucidrains/reformer-pytorch#51]
hi, I wonder if 't' should be 'kv_len'?
`return v.view(b, h, t, -1).transpose(1, 2).contiguous()`
[https://github.com/lucidrains/reformer-pytorch/blob/fde8efefe34ce30cf872e67b86e268b103d5a49b/reformer_pytorch/reformer_pytorch.py#L472](url)

**Comment by lucidrains** [comment]
Hello @opsuisppn ! So actually I return the corrected shape `(b, t, e)` from `LSHAttention`. The code that does that is here https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L358

**Comment by opsuisppn** [comment]
Thanks! Very nice work!
