### ISSUE TITLE
definition of input_attn_mask  and context_mask

### ISSUE THREAD

**Issue by opsuisppn** [lucidrains/reformer-pytorch#53]
Hi @lucidrains, in a encoder-decoder setting, consider input to decoder as target, denote encoder input length S and decoder length input T, the size of input_mask and input_attn_mask should be NxT and TxT. It is unclear context_mask should have NxS (padding) or TxS (memory)?

**Comment by lucidrains** [comment]
@opsuisppn hello! I believe it the `context_mask` going into the decoder should be NxS, and will be identical to the `input_mask` going into the encoder

**Comment by lucidrains** [comment]
@opsuisppn haha, you just made me reexamine some code, and I discovered a bug with attention chunking and masking *facepalm*

**Comment by opsuisppn** [comment]
@lucidrains :) I am testing input_mask and receive error on training *second* batch, possibly due to chunking.

**Comment by lucidrains** [comment]
@opsuisppn I think there is now a separate issue with DataParallel and reversible args and extra keyword parameters. It should work if you only work off of 1 GPU, but I'll fix the DataParallel issues by tonight!

**Comment by opsuisppn** [comment]
@lucidrains I will test with 1 gpu later. When setting input_mask to None the code works fine.

**Comment by lucidrains** [comment]
@opsuisppn thanks for pressing on this. Turns out the `SettableArgs` hack I did in order to get reversible nets working with multiple arguments is the cause. The good news is that doing a proper fix so reversible nets take more than 1 argument will lead to a speed up! Will fix this soon! Thanks for reporting this!

**Comment by opsuisppn** [comment]
Thanks! You did the hard work! :)

**Comment by opsuisppn** [comment]
@lucidrains CUDA error is gone! 👍

**Comment by lucidrains** [comment]
@opsuisppn is it working for you??

**Comment by opsuisppn** [comment]
Hi @lucidrains There is no Cuda error anymore, but the loss stopped decreasing after initial dip of about 20 batches. I am checking my model. In your example enwik8_simple I could not get as good generation as yours. How many epochs did you train?

**Comment by lucidrains** [comment]
@opsuisppn ohh that's weird, I usually see good generation at around the 10-15 hour mark. Adding axial position embedding really speeds up training by a factor too. Could you possibly share some code on the encoder / decoder task you are working on? I would like to help out if possible. I think one thing to try if the decoder isn't working well is to increase the `bucket_size` of the decoder to `128`.

**Comment by opsuisppn** [comment]
hi @lucidrains, super! It would be great to have your inputs. For a rough idea, I found a batch that a transformer takes about 30 seconds to process, the reformer model would take 5+ minutes.

**Comment by lucidrains** [comment]
@opsuisppn yea i know, the speed issues are well known, and if you have any optimization ideas, feel free to submit a PR! i've added two settings that may speed it training. `full_attn_thres` and `reverse_thres`, which would respectedly turn off LSH attention and reversibility if the batched sequence lengths ever get shorter than the designated sequence length
