### ISSUE TITLE
Not clear about the calculation of  the KQ and V vectors

### ISSUE THREAD

**Issue by shamanez** [lucidrains/reformer-pytorch#54]
Can you please explain this [line ?](https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L457)

It seems you add extra 128 units to the input sequence why is that?

**Comment by lucidrains** [comment]
@shamanez Hey! If you are referring to the memory vectors, it's actually from the All-attention paper from Facebook. 
![Screenshot from 2020-03-05 09-21-29](https://user-images.githubusercontent.com/108653/76007345-c2051200-5ec2-11ea-8cd9-17100e4ab6ee.png)

It's worked well for some of my use-cases so I've added it as a feature. You can turn it off by removing the `num_mem_kv` setting

**Comment by shamanez** [comment]
Ok got it. Actually this is really nice since it can reduce the parameters furthermore. Ine more thing, what is the intuition behind taking num_mem_kv as 128? what would happen if we increase it or decrease it?
