### ISSUE TITLE
A full Reformer image → caption example was wrong

### ISSUE THREAD

**Issue by TranTony** [lucidrains/reformer-pytorch#59]
When I try this example: A full Reformer image → caption, I found out that encoder was wrong because there was no arguments _**_axial_position_emb_**_ = True, _**axial_position_shape**_ = (32, 32), _**axial_position_dims**_ = (256, 256) in Reformer class but ReformerLM has them. Please help me verify this issue.

**Comment by lucidrains** [comment]
@TranTony ohh, you are right, I've removed it for now. Only ReformerLM class will have positional embedding support, for now

**Comment by opsuisppn** [comment]
Hi @lucidrains, I think it is nice to have positional embedding separated from Reformer class, so other approaches can be explored.

**Comment by TranTony** [comment]
@lucidrains thank you so much for your information. @opsuisppn I agree with you.

**Comment by lucidrains** [comment]
@opsuisppn ohh, what did you have in mind?

@TranTony I've used Uber's CoordConv with some success! https://eng.uber.com/coordconv/
