### ISSUE TITLE
Typo in LSHSelfAttention causing NameError exception

### ISSUE THREAD

**Issue by lduperier** [lucidrains/reformer-pytorch#61]
https://github.com/lucidrains/reformer-pytorch/blob/b73f2ffc8bdd5b39a4e0fbbd67269cc2760bd5b2/reformer_pytorch/reformer_pytorch.py#L306
`stotal_hashes` should be `total_hashes`. Thanks for the library!

**Comment by lucidrains** [comment]
Oops.. Fixed!
