### ISSUE TITLE
Predicting with Encoder-Decoder structure

### ISSUE THREAD

**Issue by nakarinh14** [lucidrains/reformer-pytorch#64]
This is a follow up from my comment in https://github.com/lucidrains/reformer-pytorch/issues/50. How do you make a prediction for a test example for encoder-decoder, after training with the code block mention in the issue?

**Comment by lucidrains** [comment]
@nakarinh14 you have to sample from the decoder, using the encoded keys from the encoder as context. you can also use the handy `TrainingWrapper`, which includes a generate function that supports nucleus and topk sampling

```python
import torch
from reformer_pytorch import ReformerLM
from reformer_pytorch.generative_tools import TrainingWrapper, top_p

DE_SEQ_LEN = 1024
EN_SEQ_LEN = 1024

encoder = ReformerLM(
    num_tokens = 20000,
    dim = 1024,
    depth = 2,
    heads = 8,
    attn_chunks = 5,
    max_seq_len = DE_SEQ_LEN,
    fixed_position_emb = True,
    return_embeddings = True
)

decoder = ReformerLM(
    num_tokens = 20000,
    dim = 1024,
    depth = 2,
    heads = 8,
    attn_chunks = 2,
    max_seq_len = EN_SEQ_LEN,
    fixed_position_emb = True,
    causal = True
)

x  = torch.randint(0, 20000, (2, DE_SEQ_LEN)).long()
enc_keys = encoder(x)

decoder = TrainingWrapper(decoder)

yi = torch.tensor([[0]]).long()
sample = decoder.generate(yi, 1024, filter_logits_fn=top_p, filter_thres=0.95) # (2, <= 1024)
# decode the sample token ids
```

**Comment by lucidrains** [comment]
@nakarinh14 I should probably just write out the full Reformer encoder / decoder into one class lol

**Comment by nakarinh14** [comment]
@lucidrains Thank you very much for the replies! I agree it would be quite nice if there's one seperate class for encoder-decoder structure :)

**Comment by lucidrains** [comment]
@nakarinh14 https://github.com/lucidrains/reformer-pytorch#reformer-encoder-decoder-architecture done!
