### ISSUE TITLE
Is enc_input_mask equal to set pad_idx and ignore_idx?

### ISSUE THREAD

**Issue by CalogeroZarbo** [lucidrains/reformer-pytorch#66]
Hi @lucidrains 
I updated the code to use your implementation of the EncDec architecture, but I ran out of memory when I set the input_mask and the context_mask accordingly in order to mask the Pad indexes.
In the previous implementation where I used this:

```
    encoder = TrainingWrapper(encoder, ignore_index=PAD_IDX).cuda()
    decoder = TrainingWrapper(decoder, ignore_index=PAD_IDX).cuda()

    encoder_engine, encoder_optimizer, trainloader, _ = deepspeed.initialize(args=cmd_args, model=encoder, optimizer=encoder_optimizer, model_parameters=encoder_params, training_data=train_dataset, dist_init_required=True)

    decoder_engine, decoder_optimizer, _, _ = deepspeed.initialize(args=cmd_args, model=decoder, optimizer=decoder_optimizer, model_parameters=encoder_params, dist_init_required=False)

    for src, trg in dataset:
            encoder_engine.train()
            decoder_engine.train()
            src = src.to(encoder_engine.local_rank)
            trg = trg.to(decoder_engine.local_rank)
            enc_keys = encoder_engine(src)
            loss = decoder_engine(trg, keys = enc_keys, return_loss = True)   
            loss.backward()
            decoder_engine.step()
            encoder_engine.step()

```
instead of this:
```   
enc_dec_engine, enc_dec_optimizer, trainloader, _ = deepspeed.initialize(args=cmd_args, model=enc_dec, optimizer=enc_dec_optimizer, model_parameters=enc_dec_params, training_data=train_dataset)

    for src, trg in dataset:
            enc_dec_engine.train()
            
            src = src.to(enc_dec_engine.local_rank)
            trg = trg.to(enc_dec_engine.local_rank)

            enc_input_mask = torch.tensor([[1 for idx in smpl if idx != PAD_IDX] for smpl in src]).bool().to(device)
            context_mask = torch.tensor([[1 for idx in smpl if idx != PAD_IDX] for smpl in trg]).bool().to(device)

            loss = enc_dec(src, trg, return_loss = True, enc_input_mask = enc_input_mask, context_mask=context_mask)

            loss.backward()

            enc_dec_engine.step()
```

I didn't run out of memory and I was assuming that the loss was computed excluding the Pad Index, did I made a mistake? What is the best way to ignore Pad Idx? 
Using the `input_mask` has the same outcome as setting the Pad Idx to ignore in the `TrainingWrapper`?
If they are equal, is there a way to use the ignore_index in the training wrapper instead of the masking techniques to save some memory also in your EncDec implementation?

Thank you in advance,
Cal

**Comment by lucidrains** [comment]
@CalogeroZarbo Hello! That's my mistake! I've made it so you can pass the `ignore_index` and `pad_value` keywords into the `ReformerEncDec` class and it will be forwarded to the training wrappers. If you are running into memory issues, it is possibly because I have increased the `bucket_size` of the decoder by default to twice the size of the `bucket_size` of the encoder (128 as opposed to 64). The reason I do this is because LSH attention forces the input sequence and the context into the same QK space, and this dilutes the actual pairing of QKs that actually matter. You can decrease this back to the original default with `dec_bucket_size = 64`

**Comment by CalogeroZarbo** [comment]
@lucidrains Ok thank you for the explanation and for the fix. Feel free to close the issue :)
