### ISSUE TITLE
`return_embedding` seems to be a no-op

### ISSUE THREAD

**Issue by erip** [lucidrains/reformer-pytorch#67]
Thanks so much for this implementation! I suspect it will be very helpful for the community. 😄 

I'm trying to use the `ReformerLM` with `return_embeddings=True` and it looks like it's effectively a [no-op](https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L657). When I try your collab with `return_embeddings=True`, `model.out` is just `Identity()` and no embedding is returned from the forward pass.

Am I using this option incorrectly or is it still a TODO?

**Comment by erip** [comment]
It looks like it might be the case that the logic in the linked code is reversed? If `not return_embeddings`, `Identity()` should be returned; otherwise return the sequential model with linear projection? Looks like a simple fix if diagnosed correctly.

**Comment by erip** [comment]
Nevermind - misread completely. Seems fine. 😄

**Comment by lucidrains** [comment]
@erip you figured it out! :D indeed, Identity is a noop class
