### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by gentaiscool** [lucidrains/reformer-pytorch#70]
Hi! Thanks for implementing a new interesting model, Reformer.

Have you got any chance to report the results on imagenet64 and enwik8-64K? It would be great if you can validate the model on them. At least to validate whether the code is implemented as it should be.

Thank you

**Comment by lucidrains** [comment]
@gentaiscool Hello and thanks for your interest! You can find a working script for enwik8 in the `examples` folder. I never did an imagenet64, but perhaps you'd like to contribute and submit a PR? :)
