### ISSUE TITLE
Which function executes the multi-attention part?

### ISSUE THREAD

**Issue by arushi-08** [lucidrains/reformer-pytorch#73]
The "Reformer Transformer" paper mentions that it focuses on attention computation, while keeping the multi-head attention computation intact. Could you tell where, (in the code),  multiple attention heads are concatenated before being passed to feedforward layer?

**Comment by lucidrains** [comment]
@arushi-08 the multi-head attention is taken care of by the `LSHSelfAttention` class. the merging of the heads happen at https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L481 they are split again and passed to the feedforward here https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L503

**Comment by L-Hugh** [comment]
> @arushi-08 the multi-head attention is taken care of by the `LSHSelfAttention` class. the merging of the heads happen at https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L481 they are split again and passed to the feedforward here https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L503

@lucidrains Thanks for your sharing! I have noticed that you divide the queries, keys and values into eight(heads) parts in the last dimension and concatenate the output of LSHAttention. However, in the original Transformers paper, it is linearly project the queries, keys and values eight times with different linear projections. Then eight output values are concatenated(the shape is [batch_size, token_len, 8*d_model]) and once again projected(the shape is [batch_size, token_len, d_model]). I think they are different. if I'm wrong, correct me please.

**Comment by arushi-08** [comment]
Please clarify this @lucidrains.

**Comment by L-Hugh** [comment]
@arushi-08 @lucidrains I'm wrong. They're identical actually.  In the original Transformers paper, The shape of Q, K, and V is [batch_size, token_len, d_model/8] (if the heads is 8), so it is the same as dividing the Q, K and V which have the shape of [batch_size, token_len, d_model] into 8 parts in the last dimension.
