### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by zhao1402072392** [lucidrains/reformer-pytorch#75]
thanks for your sharing ,it's really helpful, could I know the performance of this code, dose it achieves the performance in this reformer paper? thanks again ^_^

**Comment by lucidrains** [comment]
@zhao1402072392 I ran it on enwik8 on a sequence length of 4096 in the example. It does take longer to train, but does seem to achieve an ok perplexity after some time.

**Comment by zhao1402072392** [comment]
oh cool, the perplexity is ok , how about bleu score or other evaluation indices?

**Comment by lucidrains** [comment]
@zhao1402072392 the official Reformer team is working on translation, but apparently without LSH attention (they simply have vanilla transformers with reversible layers). Some others and I have also started to uncover some limitations to Reformer https://github.com/lucidrains/reformer-pytorch/issues/69 Please feel free use the framework to experiment, but my growing sentiment with Reformer has been more negative over the past two weeks

**Comment by zhao1402072392** [comment]
got it, thanks for your replying^_^
