### ISSUE TITLE
RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered

### ISSUE THREAD

**Issue by xijiz** [lucidrains/reformer-pytorch#76]
# Bug Report
## Environment
- Ubuntu 18.04
- Cuda 10.0
- One GPU: Nvidia 2060
- Python 3.6
- Pytorch 1.2

## Details
When I run the reformer as part of the pre-trained language model, I encountered the following error.
```bash
  x = self.reformer(x, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 631, in forward
    x = self.layers(x, arg_route = arg_route, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 151, in forward
    return _ReversibleFunction.apply(x, blocks, block_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 112, in forward
    x = block(x, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 52, in forward
    y1 = x1 + self.f(x2, record_rng=self.training, **f_args)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 27, in forward
    return self.net(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 92, in forward
    return self.fn(x, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 502, in forward
    out, attn, buckets = attn_fn_in_chunks(qk, v, **masks)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in inner_fn
    outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args]
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in <listcomp>
    outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args]
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 204, in forward
    buckets = self.hash_vectors(n_buckets, qk)
  File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 175, in hash_vectors
    offsets = torch.arange(self.n_hashes, device=device)
RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered
```

**Comment by mauceri** [comment]
Hi,

I often face this type of error when I meet gpu memory limitation. Maybe you should try to restart your gpu.

Christian Mauceri, PhD

**Comment by xijiz** [comment]
> Hi, I often face this type of error when I meet gpu memory limitation. Maybe you should try to restart your gpu. Christian Mauceri, PhD Le 26 mars 2020 à 09:13 +0100, Xiangji Zeng <notifications@github.com>, a écrit :
> […](#)
> • Ubuntu 18.04 • Cuda 10.0 • One GPU: Nvidia 2060 • Python 3.6 • Pytorch 1.2 When I run the reformer as part of the pre-trained language model, I encountered the following error. x = self.reformer(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 631, in forward x = self.layers(x, arg_route = arg_route, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 151, in forward return _ReversibleFunction.apply(x, blocks, block_kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 112, in forward x = block(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 52, in forward y1 = x1 + self.f(x2, record_rng=self.training, **f_args) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 27, in forward return self.net(*args, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 92, in forward return self.fn(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 502, in forward out, attn, buckets = attn_fn_in_chunks(qk, v, **masks) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in inner_fn outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args] File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in <listcomp> outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args] File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 204, in forward buckets = self.hash_vectors(n_buckets, qk) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 175, in hash_vectors offsets = torch.arange(self.n_hashes, device=device) RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> Hi, I often face this type of error when I meet gpu memory limitation. Maybe you should try to restart your gpu. Christian Mauceri, PhD Le 26 mars 2020 à 09:13 +0100, Xiangji Zeng <notifications@github.com>, a écrit :
> […](#)
> • Ubuntu 18.04 • Cuda 10.0 • One GPU: Nvidia 2060 • Python 3.6 • Pytorch 1.2 When I run the reformer as part of the pre-trained language model, I encountered the following error. x = self.reformer(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 631, in forward x = self.layers(x, arg_route = arg_route, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 151, in forward return _ReversibleFunction.apply(x, blocks, block_kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 112, in forward x = block(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 52, in forward y1 = x1 + self.f(x2, record_rng=self.training, **f_args) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 27, in forward return self.net(*args, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 92, in forward return self.fn(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 502, in forward out, attn, buckets = attn_fn_in_chunks(qk, v, **masks) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in inner_fn outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args] File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in <listcomp> outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args] File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 204, in forward buckets = self.hash_vectors(n_buckets, qk) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 175, in hash_vectors offsets = torch.arange(self.n_hashes, device=device) RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> Hi, I often face this type of error when I meet gpu memory limitation. Maybe you should try to restart your gpu. Christian Mauceri, PhD Le 26 mars 2020 à 09:13 +0100, Xiangji Zeng <notifications@github.com>, a écrit :
> […](#)
> • Ubuntu 18.04 • Cuda 10.0 • One GPU: Nvidia 2060 • Python 3.6 • Pytorch 1.2 When I run the reformer as part of the pre-trained language model, I encountered the following error. x = self.reformer(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 631, in forward x = self.layers(x, arg_route = arg_route, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 151, in forward return _ReversibleFunction.apply(x, blocks, block_kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 112, in forward x = block(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 52, in forward y1 = x1 + self.f(x2, record_rng=self.training, **f_args) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reversible.py", line 27, in forward return self.net(*args, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 92, in forward return self.fn(x, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 502, in forward out, attn, buckets = attn_fn_in_chunks(qk, v, **masks) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in inner_fn outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args] File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 32, in <listcomp> outputs = [fn(*c_args, **c_kwargs) for c_args, c_kwargs in all_args] File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__ result = self.forward(*input, **kwargs) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 204, in forward buckets = self.hash_vectors(n_buckets, qk) File "/home/user/.local/lib/python3.6/site-packages/reformer_pytorch/reformer_pytorch.py", line 175, in hash_vectors offsets = torch.arange(self.n_hashes, device=device) RuntimeError: tabulate: failed to synchronize: cudaErrorAssert: device-side assert triggered — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks, I am trying this method and it seems to work for now.
