### ISSUE TITLE
Error with shapes in LocalAttention

### ISSUE THREAD

**Issue by ilya16** [lucidrains/reformer-pytorch#88]
Hi, recently updated to the recent version of the package (`0.22.3`) and caught a bug with shapes in `LocalAttention`'s `forward()` method ([reformer_pytorch.py#L502](https://github.com/lucidrains/reformer-pytorch/blob/43ca29c0625fdf4585a325408a5a11b143b7c0bc/reformer_pytorch/reformer_pytorch.py#L502)) when both `num_mem_kv` and `n_local_attn_heads` are non-zero: 

```python
    501         out = torch.einsum('bhij,bhje->bhie', attn, bv)
--> 502         out = out.reshape(b, t, e)
    503         return out
    504 

RuntimeError: shape '[2, 2048, 64]' is invalid for input of size 278528
```

When any of `num_mem_kv`/`n_local_attn_heads` is zero, the model works fine. 

Minimal example for reproducing the error:

```python
import torch
from reformer_pytorch import ReformerLM

num_tokens, seq_len = 1024, 2048
model = ReformerLM(
    num_tokens=num_tokens,
    dim=512,
    depth=6,
    max_seq_len=seq_len,
    num_mem_kv=128,
    n_local_attn_heads=2,
).cuda()

x = torch.randint(0, num_tokens, (1, seq_len)).long().cuda()
y = model(x)
```

Hope that helps! Thanks for your work on the package!

**Comment by lucidrains** [comment]
@ilya16 thank you for reporting! are you having any success with local attention heads mixed in?  i was hoping the local attention would allow for specialization of the lsh attention to more long range and yield better quality

**Comment by lucidrains** [comment]
@ilya16 i need more GPUs, so many experiments queued up :(

**Comment by lucidrains** [comment]
https://github.com/lucidrains/reformer-pytorch/commit/71fe0482633e4cf0bf714505a169d55a2da50ed7 fixed!

**Comment by ilya16** [comment]
@lucidrains for now I did not experiment much with local attention, just got back to Reformer and updated to the recent version. If I find any strange or positive behaviour, I will report it.

**Comment by lucidrains** [comment]
@ilya16 please do!
