### ISSUE TITLE
Question: Chunking input is expected behavior in the standard reformer?

### ISSUE THREAD

**Issue by hotohoto** [lucidrains/reformer-pytorch#94]
Recently I started to read the reformer paper and your great PyTorch implementation.

And I found this.

![image](https://user-images.githubusercontent.com/5404902/81727149-7626a880-94c3-11ea-8c62-e8ea5c142a1b.png)

To me, it sounds like the implementation [here](https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reversible.py#L51) could be wrong since `both x_1 and x_2 have size d_model` might mean that we need to duplicate them instead of chunking. What do you think? 🤔 

Trax implementation is much more difficult for me, so I couldn't point out the corresponding spot precisely.

Or it is just splitting inputs which was duplicated somewhere else? 😮

**Comment by lucidrains** [comment]
@hotohoto it was duplicated here! https://github.com/lucidrains/reformer-pytorch/blob/master/reformer_pytorch/reformer_pytorch.py#L783
