### ISSUE TITLE
Applications for reformer model

### ISSUE THREAD

**Issue by lucky-23** [lucidrains/reformer-pytorch#95]
I was wondering if reformer model would be a good choice for video captioning?

**Comment by lucidrains** [comment]
@lucky-23 Attention is all you need

**Comment by lucidrains** [comment]
Video is still difficult, not a single big company has been able to do it, and there's even some evidence that perhaps we are just an order of magnitude compute away from being able to deal with it as efficiently as images. https://papers.nips.cc/paper/8303-high-fidelity-video-prediction-with-large-stochastic-recurrent-neural-networks.pdf (Notice the comment on The Bitter Lesson in the paper)

If you do go the Attention route for video, I have found great success with https://openreview.net/pdf?id=H1e5GJBtDr to cut down the amount of attention you need to do.

**Comment by lucidrains** [comment]
If Reformer is too slow, you can also try another implementation for sparse attention here https://github.com/lucidrains/sinkhorn-transformer It comes with its own problems, but so far I think I have bandaid-ed most of them

**Comment by lucky-23** [comment]
Thanks a lot for your suggestion
