### ISSUE TITLE
Experiment with Ranger, the state of the meta optimizer 

### ISSUE THREAD

**Issue by LifeIsStrange** [lucidrains/reformer-pytorch#98]
https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer
Reformer could get better accuracy from Ranger and from the Mish activation function. 
This is, IMHO a promising research direction.

**Comment by lucidrains** [comment]
@LifeIsStrange Sure! You can always use Ranger with Reformer. You can also plugin Mish with https://github.com/lucidrains/reformer-pytorch#customizing-feedforward

**Comment by CalogeroZarbo** [comment]
Hi everyone,
I'm actually using Ranger and Mish with Reformer Pytorch with good results.
To be more specific I'm using RangerLars (search for over9000.py).
Also I suggest you to use DeepSpeed and Zero Optimizer from Microsoft which
would optimize even more the Comp Time and Parameters Distribution Strategy
over multiple GPUs. The fix to make RangerLars + Mish compatible with
Microsoft DeepSpeed I made them personally and they are now in the master
branch. Reformer Pytorch is already compatible with DeepSpeed by default
(kudos to Phil!)

Cheers,
Cal

Il giorno sab 13 giu 2020 alle ore 00:44 Phil Wang <notifications@github.com>
ha scritto:

**Comment by LifeIsStrange** [comment]
@CalogeroZarbo interesting, this is the first time I hear someone actually trying theses with a transformer!
You mention *pretty good results*, could you illustrate how much accuracy can you gain versus the baseline?

So you use https://github.com/mgrankin/over9000 instead of https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer
Be aware that over9000 is not actively maintained, for example the lessw2020 version has gained support for "Gradient centralization" which over9000 hasn't. 

I had never heard of DeepSpeed and Zero Optimizer, thanks for sharing!
